const AuthClass = require('../../../../Middeware/AuthMiddleware');
const post = require('./post');
const { GetBlogList } = require('../../../../Controller/user/editblog');
const editblog = require('express').Router();
const Auth = new AuthClass();
editblog.use(Auth.authenticate('blogtee;accessToken'));
editblog.get('', GetBlogList);
editblog.get('/search');
editblog.use('/post', post);
module.exports = editblog;
